// GENERATED by scripts/assets/images.py - do not edit by hand.
// Intrinsic dimensions are recorded so every <img> can reserve its box
// and the page never shifts while photographs load.

export interface GeneratedImage {
  slug: string;
  widths: number[];
  width: number;
  height: number;
}

export const generatedImages = {
  'bricks-stack': {
    slug: 'bricks-stack',
    widths: [640, 960, 1280],
    width: 1280,
    height: 960,
  },
  'cement-brands': {
    slug: 'cement-brands',
    widths: [320, 480, 640, 960],
    width: 1280,
    height: 960,
  },
  'cement-godown': {
    slug: 'cement-godown',
    widths: [320, 480, 640, 960],
    width: 1280,
    height: 960,
  },
  'cement-stock': {
    slug: 'cement-stock',
    widths: [320, 480, 640],
    width: 959,
    height: 719,
  },
  'visiting-card': {
    slug: 'visiting-card',
    widths: [480, 720, 960],
    width: 1041,
    height: 652,
  },
} as const satisfies Record<string, GeneratedImage>;

export type GeneratedImageSlug = keyof typeof generatedImages;
